---
- name: Apply proxy settings to ~/.bash_proxy
  template:
    src: bash_proxy.j2
    dest: "{{ ansible_env.HOME }}/.bash_proxy"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
...
